#!/bin/bash

npm run build
git add .
git commit -m "release"
npm run copy
cp dist ../.
git checkout gh-pages
mv ../dist/*.* .
git add .
git commit -m "release"
git push origin gh-pages
rm ../dist
git checkout master
